language: go

node_js: node

sudo: false

addons:
  apt:
    packages:
      - nodejs

os:
  - linux

env:
  - TRAVIS_NODE_VERSION="v8.11.0" TRAVIS_ELM_VERSION="0.19.0" TRAVIS_ELM_TEST_VERSION="0.19.0-beta8"

before_install:
  #- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

install:
  - set -e
  - ./install_protobuf
  - export PATH=$PATH:$PWD/protoc/bin
  - protoc --version
  - node --version
  - npm --version
  - npm install -g elm@$TRAVIS_ELM_VERSION
  - elm --version
  - npm install -g elm-test@$TRAVIS_ELM_TEST_VERSION
  - elm-test --version

script: 
  - set -e
  - ./run_elm_tests
  - ./run_diff_tests
