language: go

sudo: false

addons:
  apt:
    packages:
      - nodejs

env:
  - TRAVIS_NODE_VERSION="v7.2.1"

cache:
  directories:
    - sysconfcpus
    - protoc

before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - ./install_sysconfcpus
  - ./install_protobuf

install:
  - export PATH=$PATH:$PWD/protoc/bin
  - go get -t -v ./protoc-gen-elm
  - protoc --version
  - node --version
  - npm --version
  - npm install -g elm
  - npm install -g elm-test
  - mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
  - printf '%s\n\n' '#!/bin/bash' 'echo "Running elm-make with sysconfcpus -n 2"' '$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old "$@"' > $(npm config get prefix)/bin/elm-make
  - chmod +x $(npm config get prefix)/bin/elm-make

script: ./run_tests
